GET localhost:8080/todos

> {%
if(response.body.length > 0) {
  client.assert(response.body[0].id, "Id shouldn't be null");
  client.global.set("todoId", response.body[0].id);
}
 %}

###

GET localhost:8080/todos
Accept: text/event-stream

###

POST localhost:8080/todos
Content-Type: application/json

{
  "text": "Prepare Virtual Insights session",
  "assignee": "Lars"
}

> {%
client.assert(response.body.id, "Id shouldn't be null");
client.global.set("todoId", response.body.id);
%}

###

POST localhost:8080/todos
Content-Type: application/json

{"assignee":"","text":"","completed":false,"deleted":false}

> {%
client.assert(response.body.id, "Id shouldn't be null");
client.global.set("todoId", response.body.id);
%}

###

PUT localhost:8080/todos/{{todoId}}
Content-Type: application/json

{
  "text": "Prepare Virtual Insights session",
  "assignee": "Lars",
  "completed": true
}

###

DELETE localhost:8080/todos/{{todoId}}
